services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./server:/app

  # CLIENTS
  client_one:
    build:
      context: ./client_one
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./client_one:/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - server

  client_two:
    build:
      context: ./client_two
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./client_two:/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - server